

local members = {
    referees = {
		'Dagaldo',
		'armeniodbest',
		'J_Melo',
		'X_Wrath',
		'iGatiZ',
		'Mxarkii',
		'C0nfIict',
		'ReaiisticRainbow',
		'rapp1d',
		's1rhands',
		'xKioshix',
		'SuhasnrioRBLX',
		'jadot1212',
		'jani_tuppurainen',
		'Clampaldo',
		'FireDarkNinja123',
		'iFlareJr',
		'Joshh_x',
		'DefinetlyKxnetic',
		'heqiz',
		'Physics2k',
		'Nisay_x',
		'MrVoItzz',
		'abdul251',
		'liitvy',
		'Vaxorez_Dynamic',
		'wildhair4u',
		'LostFIames',
		'RunnerStefanSG',
		'Visxiion',
		'swish_x',
	},
	stadiumpass = {
		'x86Havoc',
		'iiPrinceBata',
		'FxsionHavoc',
		'Terrier_Jayy',
		'Irish_ferret',
		'FuturisticScars',
		'RobloxClubMajus',
		'Dap000',
		'DesirxdLuke',
		'Drakoberk',
		'Rz_ec',
		'1nzz',
		'Visxiion',
	},
	banned = {
		'PatrickWheels',
		'darksideday1',
		'NucIeracticPepi',
		'Tripie_D',
		'all_darksideday1',
	},
	adminstadiumpass = { --Stadium pass for those with admin higher than VIP so it doesnt conflict
		'IcedVapour',
		'alfieboss8',
		'RO_Football',
		'smilekyle123456',
		'hamzariasat',
		'Lord_Mewtwo',
		'SuhasnrioRBLX',
		'Shamas269',
		'1XxhassanxX1',
		'josh67231',
		'DeadIy_Strike',
		'abdul251',
		'Shamaaba',
		'DefinetlyKxnetic',
		'Dagaldo',
		'MrVoItzz',
		'DxpressedSnow',
		'wildhair4u',
		'LostFIames',
	},
	airpods = {
		'Yirelith',
		'4rob7',
		'Earth_Quake',
	},
}

return members
